# RedHat specific package installations
- include: RedHat.yml
  when: (ansible_os_family == "RedHat") and not use_percona_mongodb

# Debian specific package installations
- include: Debian.yml
  when: (ansible_os_family == "Debian" or ansible_os_family == "Linuxmint") and not use_percona_mongodb

- include: Percona_mongo.yml
  when: use_percona_mongodb
